services:
  # Django Backend
  - type: web
    name: django-bookstore-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookstore.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: bookstore-db
    databaseName: bookstore
    user: bookstore_user
    plan: free
